### ISSUE TITLE
[Mac OS X Lion] Colors look off, downloads button is wrong.

### ISSUE THREAD

**Issue by gazecube** [Lootyhoof/xmoon#2]
I've noticed that some behaviours of the theme don't match the Mac version of firefox 4+, most notably the Downloads button, colors, and some widget sizes.
Firefox 14:
![Screen Shot 2023-10-21 at 10 04 39 PM](https://github.com/Lootyhoof/xmoon/assets/33785843/eaacb6ac-657b-42d0-bae0-d9654b27940a)
Pale Moon with XMoon theme enabled:
![Screen Shot 2023-10-21 at 10 04 42 PM](https://github.com/Lootyhoof/xmoon/assets/33785843/e1a35bae-3685-4f9d-b125-6b6d8608343b)

**Comment by gazecube** [comment]
I did some "research" and I think the Mac version of Firefox uses the native UI widgets found in Mac OS X. Not sure if the proper theme from the OS X version of Firefox can be ported, but I know **nothing** about firefox theming and addons in general, so it might be possible.

**Comment by Lootyhoof** [comment]
I can't recall properly but I believe this uses Snow Leopard colours. I don't use any native widgets to get the actual correct ones though as this theme is meant to be multi platform and provide a similar look everywhere.

This is out of scope. The only theme I've made that provides native macOS styling is the default one.
